### ISSUE TITLE
Benchmark 

### ISSUE THREAD

**Issue by eric-haibin-lin** [EccentricLoggers/peloton#43]
[Setup Peloton on MemSQL machine](https://github.com/EccentricLoggers/peloton/wiki/Server-Setup-on-MemSQL)

**Comment by eric-haibin-lin** [comment]
Micro benchmark (Before tuning, no wait, 15GB data, No skew in data)

<img width="576" alt="screen shot 2016-04-21 at 2 26 21 pm" src="https://cloud.githubusercontent.com/assets/5545640/14719946/0df73d10-07cd-11e6-9b8d-17d497b6d98c.png">

<img width="584" alt="screen shot 2016-04-21 at 2 23 44 pm" src="https://cloud.githubusercontent.com/assets/5545640/14719937/f5835cc8-07cc-11e6-9e01-2f4b9bce3b0e.png">

<img width="600" alt="screen shot 2016-04-22 at 6 16 12 pm" src="https://cloud.githubusercontent.com/assets/5545640/14756325/6a1c09a6-08b6-11e6-8541-e7c0dc6dadfa.png">

**Comment by yingjunwu** [comment]
Hi, I ran ycsb benchmark in my branch and it works fine. probably I have fixed certain bugs when refactoring the code :-) the throughput I got is much higher (2-3x) than yours. I ran the experiments on a virtual machine. I will test the scalability later.

**Comment by eric-haibin-lin** [comment]
@yingjunwu I pulled in your `mvcc-old-to-new` branch this afternoon and re-ran the ycsb micro benchmark:

<img width="478" alt="screen shot 2016-04-23 at 10 29 21 pm" src="https://cloud.githubusercontent.com/assets/5545640/14765153/df5bcfc0-09a2-11e6-955c-25a822292c10.png">

**Comment by yingjunwu** [comment]
@eric-haibin-lin my branch is `mvcc-new-to-old`... the GC is disabled by default. You may enable it by change the parameter in line: https://github.com/yingjunwu/peloton/blob/mvcc-new-to-old/src/backend/gc/gc_manager_factory.h#L22 to `GC_TYPE_VACUUM`. Plus, you need to enlarge queue size to, say, 100,000 set in line: https://github.com/yingjunwu/peloton/blob/mvcc-new-to-old/src/backend/gc/gc_manager.h#L31and L32.

In fact, the single-thread GC does not work well. My new YCSB can report the throughput for every 0.1 seconds. You can see how the GC influence the system throughput.

**Comment by yingjunwu** [comment]
@eric-haibin-lin I highly suggest you to check the throughput log recorded in outputfile.summary. GC is very important in multi-versioned systems. Hyrise's design, which is implemented in Joy's old branch, does not implements GC. Plus, it does not distinguish primary index from secondary indexes. In addition, its measurement scheme implemented in the old-version YCSB benchmark renders the reported numbers meaningless.

**Comment by eric-haibin-lin** [comment]
50% Update with garbage collection ON.  Before tuning flush frequency. 

<img width="373" alt="screen shot 2016-04-26 at 11 10 47 am" src="https://cloud.githubusercontent.com/assets/5545640/14823211/af5d4fac-0b9f-11e6-909e-a1c4ad05dba9.png">

100% Update with garbage collection ON.  Before tuning flush frequency. 

<img width="436" alt="screen shot 2016-04-26 at 11 44 37 am" src="https://cloud.githubusercontent.com/assets/5545640/14824508/4b926b42-0ba4-11e6-92e4-e51cb6070824.png">

**Comment by yingjunwu** [comment]
Not sure whether you have merged my PR to the master branch at cmudb, but the result seems to be reasonable, as we found that there might be some bottlenecks on the storage layer.

**Comment by yingjunwu** [comment]
Btw, what's the scale factor?

**Comment by eric-haibin-lin** [comment]
I only merged with the `new-to-old` branch, and turned on GC as you mentioned previously. I haven't merged with cooperative GC branch yet. The scale factor is 1. What scale do you usually test with?

**Comment by yingjunwu** [comment]
Reasonable. Now you can try to merge with my mvcc-cooperative-gc branch and see what will happen. You can set the scale factor to 10 or even larger.
