### ISSUE TITLE
Checkpoint benchmark

### ISSUE THREAD

**Issue by eric-haibin-lin** [EccentricLoggers/peloton#56]
Run YCSB 100% Update workload for 1000 seconds, with scale factor = 1000 (1M Tuples of 10 columns), resulting in 61GB of memory usage(including indexes, etc.) 

Before checkpoint: 30GB logs
After checkpoint: 32MB logs and 1.1GB checkpoint.

**Comment by MattPerron** [comment]
Wow. That's perfect.
